-- AlterEnum
ALTER TYPE "ActivityLogType" ADD VALUE 'ADMIN_USER_EMAIL_CHANGED';
ALTER TYPE "ActivityLogType" ADD VALUE 'ADMIN_USER_PASSWORD_RESET_SENT';
ALTER TYPE "ActivityLogType" ADD VALUE 'ADMIN_USER_PASSWORD_CHANGED';
ALTER TYPE "ActivityLogType" ADD VALUE 'ADMIN_USER_2FA_DISABLED';
